### ISSUE TITLE
Why do people’s faces collapse so badly in my generated videos?

### ISSUE THREAD

**Issue by Maycbj** [dvlab-research/ControlNeXt#1]
How to align the face of the reference with the pose?

Input image:
![xixi3](https://github.com/dvlab-research/ControlNeXt/assets/19340566/9c7db7ce-5a05-4a83-9fcd-3ef765433a6e)
https://github.com/dvlab-research/ControlNeXt/assets/19340566/3fb5664a-fe80-40df-9fcb-6cbb78f6f540

![xixi2](https://github.com/dvlab-research/ControlNeXt/assets/19340566/4ec4789f-3115-4da1-bc79-2b24540d1419)
https://github.com/dvlab-research/ControlNeXt/assets/19340566/d560e8f7-d779-4da3-8fb4-a87479d2bd9a

**Comment by Pbihao** [comment]
Hello, thank you for your interest in our work!

Currently, our work does not specifically address IP consistency. When the face is not aligned with the pose, SVD can result in significant loss.

This issue can be easily resolved by adding a post-processing step for face enhancement, such as [FaceFusion](https://github.com/facefusion/facefusion).
And the alternatives such as AnimateAnyone also uses such tricks through their demos

We will consider incorporating IP consistency training after completing our paper.

**Comment by Pbihao** [comment]
We also add the introduction of how use the face enhancement for the inference, more details can refer to [Inference of SVD](https://github.com/dvlab-research/ControlNeXt/tree/main/ControlNeXt-SVD?#inference).

We use your example for demo, below is the result:

https://github.com/dvlab-research/ControlNeXt/assets/22709028/79729e29-7818-4116-86ad-4c68f55ae7d3

We initially did not plan to address IP consistency since related tools are already very comprehensive.

**Comment by aleeyang** [comment]
> Hello, thank you for your interest in our work!
> 
> Currently, our work does not specifically address IP consistency. When the face is not aligned with the pose, SVD can result in significant loss.
> 
> This issue can be easily resolved by adding a post-processing step for face enhancement, such as [FaceFusion](https://github.com/facefusion/facefusion). And the alternatives such as AnimateAnyone also uses such tricks through their demos
> 
> We will consider incorporating IP consistency training after completing our paper.

is there any training method can improve the consistency of id in temporal dimension?
