### ISSUE TITLE
Training script for sdxl controlnext

### ISSUE THREAD

**Issue by universewill** [dvlab-research/ControlNeXt#13]
When will the Training script for sdxl controlnext be released?

**Comment by Pbihao** [comment]
@Eugeoter

**Comment by SodaLee** [comment]
+1

**Comment by Pbihao** [comment]
The training scripts for SVD and SDXL will be released soon. We are currently in the process of preparing them.

**Comment by Eugeoter** [comment]
> When will the Training script for sdxl controlnext be released?

Thanks for your like and sorry for the delay! 
I've just released the training code at: https://github.com/dvlab-research/ControlNeXt/tree/main/ControlNeXt-SDXL-Training
Ask if you have any question :D
