### ISSUE TITLE
ControlNeXt-SVD - About Face Detection Problem

### ISSUE THREAD

**Issue by educator-art** [dvlab-research/ControlNeXt#16]
Hello

The other day, I checked the video of a person moving by using "ControlNeXt-SVD" and "facefusion" on the "T4 GPU" of Google Colab.
I was able to experience it as per the document. Thank you.

I have one question.

If you use an anime character for a reference image, the face will crumble.
so, I tried to see if I could fix my face with FaceFusion.

I tried a few models of Face Analyser and the results were the same.

>face analyser:
  --face-detector-model {many,retinaface,scrfd,yoloface,yunet} 

Question: 
Would this problem be solved if we could prepare a model for face detection of anime characters?
Or are there any considerations at the "ControlNeXt-SVD" stage?

※ Sorry, This text uses a translation tool.

**Comment by Pbihao** [comment]
Hello, thanks for your interests first!

That's a great question. Currently, most models for video generation (Ours), face detection (Yolo), pose estimation (DWPose), and face swapping (FaceFusion), are trained primarily on real-world data. As a result, they may not be fully compatible with anime characters.

The challenge lies in the scarcity of high-quality training data for anime characters, which makes it difficult to develop models specifically tailored for this domain.

Our ControlNeXt-SDXL is trained on the animate data, maybe you will be interested.

**Comment by ljc02** [comment]
Hi, can you share the colab link of ControlNeXt? Thanks a lot

**Comment by educator-art** [comment]
I'm sorry, but I haven't made the Colab link public. I recommend trying it yourself while referring to the documentation.
I referred to the following link.

https://github.com/dvlab-research/ControlNeXt/tree/main/ControlNeXt-SVD

※ Sorry, This text uses a translation tool.
