### ISSUE TITLE
Which version of Python is used to train SVD-v2?

### ISSUE THREAD

**Issue by JWargrave** [dvlab-research/ControlNeXt#24]
Which version of Python is used to train SVD-v2? Is it crucial for training converge? (As you mentioned [here](https://github.com/dvlab-research/ControlNeXt/blob/main/ControlNeXt-SVD-v2-Training/README.md), the version of dependencies matters.)

**Comment by Pbihao** [comment]
Hello, thanks for your interests for our work.

We adopt:
Python 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] on linux
