### ISSUE TITLE
About trainable parameters of UNet r".*attn2.*to_out.*"

### ISSUE THREAD

**Issue by oozz-sj** [dvlab-research/ControlNeXt#27]
Hi authors, thanks for your interesting works. I note that the trainable parameters of UNet is r".\*attn2.\*to_out.\*", which actually is the cross-attention, not self-attention (see https://github.com/huggingface/diffusers/blob/5090b09d48ee958eb07ab4d979737944682552dd/src/diffusers/models/attention.py#L487C12-L487C22).
However, in your paper, you said Partial tuning on Self-Attention. Is there any difference betten them? Thanks

**Comment by Pbihao** [comment]
This is mainly to reduce the number of parameters and shouldn't cause significant issues or differences. You can also choose which part to train yourself; training just a portion of 'to_out' is sufficient.

**Comment by Pbihao** [comment]
Thanks for your interests!

**Comment by Pbihao** [comment]
In our experiments, we observed no significant differences. Initially, we trained all 'to_out' linear layers (both self- and cross-), and then trained only a subset. 

However, you can also experiment on your own, as we have released all the training scripts. The convergence is rapid.
