### ISSUE TITLE
is Controlnet just used on the first block of down_block

### ISSUE THREAD

**Issue by xiaohutongxue-sunny** [dvlab-research/ControlNeXt#28]

**Comment by xiaohutongxue-sunny** [comment]
![Uploading 2024-08-22 15-36-59 的屏幕截图.png…]()

**Comment by Pbihao** [comment]
Thank you for your interest.

Unfortunately, I can't load your image.

Regarding your question: the processed controls are injected after the first block and before the second block. For more details, please refer to our code directly.
