### ISSUE TITLE
HTTP Error 404 when training ControlNeXt SD 1.5

### ISSUE THREAD

**Issue by ManuelSerna** [dvlab-research/ControlNeXt#38]
Hello,

Thank you for providing this work. I tried training on stable diffusion 1.5 training command, specifically, 

```
CUDA_VISIBLE_DEVICES=0,1,2,3 accelerate launch --main_process_port 1234 train_controlnext.py \
 --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
 --output_dir="checkpoints" \
 --dataset_name=fusing/fill50k \
 --resolution=512 \
 --learning_rate=1e-5 \
 --validation_image "examples/conditioning_image_1.png" "examples/conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --checkpoints_total_limit 3 \
 --checkpointing_steps 400 \
 --validation_steps 400 \
 --num_train_epochs 4 \
 --train_batch_size=6 \
 --controlnext_scale 0.35 \
 --save_load_weights_increaments 
```

However, I get the below 404 error.

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/tokenizer/tokenizer_config.json 
```

It seems that this address no longer points to something that exists, or could be mistakenly placed as an arg? There is probably an alternative but I am not sure which one is ok to use with the codebase. 

Thank you for the support!

**Comment by Eugeoter** [comment]
It seems to be relevant to a news that runwayml (the one who released sd1.5) deleted all his models (include sd1.5) recently.
So you may download it's checkpoint from '[v1-5-pruned-emaonly.safetensors](https://huggingface.co/benjamin-paine/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.safetensors)' and set `--pretrained_model_name_or_path` to it.

**Comment by ManuelSerna** [comment]
Thanks for the help! SD 1.5 can train!
