### ISSUE TITLE
SVD training code?

### ISSUE THREAD

**Issue by xiao2mo** [dvlab-research/ControlNeXt#4]
Hi, thanks for your great work.
When will it be released.

**Comment by Pbihao** [comment]
Hello! Thanks for your interest to our work!

We will consider to release the training code after finishing the paper.

**Comment by jiachen0212** [comment]
> Hello! Thanks for your interest to our work!
> 
> We will consider to release the training code after finishing the paper.

Based on your work, segment training code based on sd1.5, would you consider open-sourcing it? ~
