### ISSUE TITLE
Only train controlnext? 

### ISSUE THREAD

**Issue by Phoenix724** [dvlab-research/ControlNeXt#43]
If only ControlNeXt is trained without training the UNet, what would be the outcome? Has anyone conducted related experiments?

**Comment by Eugeoter** [comment]
In my opinion, the duty of the ControlNeXt is adding control signal into latents and the UNet is utilizing the signal. When training ControlNeXt only, we can still control image but, since it replies on the talent of the original UNet, the effect will be weaker.
