### ISSUE TITLE
Dependencies conflict for SVD-V2-training

### ISSUE THREAD

**Issue by zeezou-isee** [dvlab-research/ControlNeXt#47]
I appreciate this fantastic work and grateful for open source !

Unfortunately, when I wanna reproduce this project and train this model on my own data, I  meet a problem at my first step to install a new environment. I install the python==3.11.8 according to issue[#24](https://github.com/dvlab-research/ControlNeXt/issues/24). Then I apply code `pip install -r requirements.txt`(cd ~/ControlNeXt/ControlNeXt-SVD-v2-Training). I meet server dependencies conflicts. 

I try to change different versions for the raised-error-packages, however , it's too many to correct them all.

So I sincerely ask author to update the environments. Thanks for your wonderful work  again! @Pbihao

**Comment by junsukha** [comment]
In my case, I installed only major dependencies as the author suggested: torch, accelerator, deepspeed, ...
For now I can run the training bash script at least.
I suggest to install other dependencies on the fly.
