### ISSUE TITLE
contrlnext-sdxl load safetensors error

### ISSUE THREAD

**Issue by JohnsonXi** [dvlab-research/ControlNeXt#5]
<img width="1026" alt="image" src="https://github.com/dvlab-research/ControlNeXt/assets/51151728/ee74c271-e2a0-4ac2-ba17-32b9f39e9199">
I succeeded in running controlnext-sd1.5, but can not on SDXL, the code of SDXL load model  is different from SD1.5.

**Comment by Pbihao** [comment]
@Eugeoter

**Comment by RobertLau666** [comment]
I also encountered the same problem, I ask for an answer please.

**Comment by Eugeoter** [comment]
@JohnsonXi Fixed. Sorry for the delay.
@RobertLau666 My bad. We changed the model structure for SDXL recently to make it lighter. Please update the code to the newest version and re-download the weight from https://huggingface.co/Pbihao/ControlNeXt.

**Comment by RobertLau666** [comment]
Nice, but the following line is still needed
```
self.vae = AutoencoderKL.from_pretrained("madebyollin_sdxl-vae-fp16-fix", torch_dtype=torch.float16).to(device)
```
result is as below, better
<img width="859" alt="截屏2024-07-12 23 16 41" src="https://github.com/user-attachments/assets/7b4db712-b5fa-483c-8450-9245d6ad7c99">

**Comment by Eugeoter** [comment]
> Nice, but the following line is still needed
> 
> ```
> self.vae = AutoencoderKL.from_pretrained("madebyollin_sdxl-vae-fp16-fix", torch_dtype=torch.float16).to(device)
> ```
> 
> result is as below, better <img alt="截屏2024-07-12 23 16 41" width="859" src="https://private-user-images.githubusercontent.com/18099350/348311062-7b4db712-b5fa-483c-8450-9245d6ad7c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzM5NDksIm5iZiI6MTcyMTAzMzY0OSwicGF0aCI6Ii8xODA5OTM1MC8zNDgzMTEwNjItN2I0ZGI3MTItYjVmYS00ODNjLTg0NTAtOTI0NWQ2YWQ3Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDA4NTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMmI2ODI0MWVlY2E5ODQ0Y2M2MjhiMDRlNTU0YjE4YzA4ZGI2NmUwYzhmYWY5MWQ4OTQ3NmExZWIwZGQ0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ckz-FpIhr-dZapaxZc0YPtiI_LyPo6sHi_-AX6S-VII">

I see. Thanks for the comment!
