### ISSUE TITLE
[BUG] mixed_precision issue of Training Modules

### ISSUE THREAD

**Issue by oneThousand1000** [dvlab-research/ControlNeXt#54]
The two lines should be commented out: 
https://github.com/dvlab-research/ControlNeXt/blob/24355d8d9da3cfe44119223e881f97205cfb418e/ControlNeXt-SD1.5-Training/train_controlnext.py#L958

https://github.com/dvlab-research/ControlNeXt/blob/24355d8d9da3cfe44119223e881f97205cfb418e/ControlNeXt-SDXL-Training/train_controlnext.py#L1151 

For training modules, they are required to be in fp32. 

Otherwise, when training with --mixed_precision="fp16", the following error is triggered:
ValueError: Attempting to unscale FP16 gradients.

**Comment by Eugeoter** [comment]
I just fixed it in https://github.com/dvlab-research/ControlNeXt/commit/16478074109ee080d1651aa216517ec1d5d1f13f.
Thanks.

**Comment by liuyang12** [comment]
Thanks for the question @oneThousand1000 and the quick fix @Eugeoter . I have exactly the same issue while training `ControlNeXt-SD1.5` with the example `fusing/fill50k` dataset.

It worked fine for the first a few steps and the loss quickly got `nan` and would never come back. The original code is based on the diffusers example of [ControlNet training](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py) and [Accelerate](https://huggingface.co/docs/accelerate/en/index) for mixed precision training and inference. I am curious why it still needs a [fix](https://github.com/dvlab-research/ControlNeXt/commit/16478074109ee080d1651aa216517ec1d5d1f13f) by replacing `accelerator.scaler._unscale_grads_` to make mixed precision training work?

```
- INFO - __main__ - Initializing controlnext weights from unet
- INFO - __main__ - ***** Running training *****
- INFO - __main__ -   Num examples = 50000
- INFO - __main__ -   Num batches each epoch = 1563
- INFO - __main__ -   Num Epochs = 4
- INFO - __main__ -   Instantaneous batch size per device = 8
- INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 32
- INFO - __main__ -   Gradient Accumulation steps = 1
- INFO - __main__ -   Total optimization steps = 6252

Steps:   0%|          | 0/6252 [00:00<?, ?it/s]
Steps:   0%|          | 1/6252 [00:03<6:02:35,  3.48s/it]
Steps:   0%|          | 1/6252 [00:03<6:02:35,  3.48s/it, loss=0.00671, lr=0.0001]
Steps:   0%|          | 2/6252 [00:04<3:02:36,  1.75s/it, loss=0.00671, lr=0.0001]
Steps:   0%|          | 2/6252 [00:04<3:02:36,  1.75s/it, loss=nan, lr=0.0001]    
Steps:   0%|          | 3/6252 [00:04<2:01:53,  1.17s/it, loss=nan, lr=0.0001]
Steps:   0%|          | 3/6252 [00:04<2:01:53,  1.17s/it, loss=nan, lr=0.0001]
Steps:   0%|          | 4/6252 [00:04<1:33:19,  1.12it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 4/6252 [00:04<1:33:19,  1.12it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 5/6252 [00:05<1:17:41,  1.34it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 5/6252 [00:05<1:17:41,  1.34it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 6/6252 [00:05<1:08:10,  1.53it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 6/6252 [00:05<1:08:10,  1.53it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 7/6252 [00:06<1:02:01,  1.68it/s, loss=nan, lr=0.0001]
Steps:   0%|          | 7/6252 [00:06<1:02:01,  1.68it/s, loss=nan, lr=0.0001]
```

**Comment by Luciennnnnnn** [comment]
@liuyang12 Do you have any ideas now? I'm also curious about this. @Eugeoter Could you please provide a explanation?
