### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by Nojahhh** [dvlab-research/ControlNeXt#8]
Hi, thanks for sharing your work. I just tried it and it works great.

I had to install two dependacies when I did a fresh install in a virtual environment in windows, I thought you might want to add these to your requirements file.

The depandacies are:
**einops
decord**

Looking forward seeing your future releases!

**Comment by weilu4606** [comment]
you can pip install, note: i am in the environment of linux, so you can install wsl to infer.

**Comment by Nojahhh** [comment]
I can see that you've added them. Great, thanks!
Closing this now.
